decoration {
    shadow {
    color = rgba(48463d55)
    color_inactive = rgba(48463d11)
    }
}

plugin {
    hyprbars {
        bar_color = rgb(48463d)
        col.text = rgb(c2bda6)

        hyprbars-button = rgb(48463d), 30, ◬, hyprctl dispatch killactive
        hyprbars-button = rgb(48463d), 30,▽, hyprctl dispatch fullscreen 1        
    }
}

misc {
    disable_hyprland_logo = true
    background_color = 0xCDC8B0
}