exec=fish -c "set -Ux COLORFILE $yorha/colors_fish_light" && pkill -USR2 fish
exec=fish -c "set -Ux STARSHIP_CONFIG $yorha/components/starship.toml"
exec=fish -c "set -Ux HYPRLAND_THEME $yorha"
exec-once=pkill ags
exec=sleep 1 && ags -c $yorha/components/ags/config.js
exec-once=hyprpm reload -n
exec-once=systemctl --user start hyprpolkitagent
exec-once = hypridle

bind=Super,v,exec,ags -b player -t player
bind=Super,space,exec,$yorha/scripts/show_desktop
bind=Super,Super_L,exec,hyprlauncher

####################################################################
# setting these here will override the values in main hyprland.conf
$DRUN=ags -b settings -t settings
$SCREENSHOT=$yorha/scripts/screenshot $yorha
$LOCK=$yorha/scripts/lock

$TERM=footclient -o shell="fish -C 'source $yorha/components/fish/theme.fish'"
$TERMSERVER=foot -s -c $yorha/components/foot.ini # -o shell="fish -C 'source $yorha/components/fish/theme.fish'"
$TERMFLOAT=$TERM --title fly_is_foot -w 1067x630
####################################################################

source = $yorha/colors_hypr_light.conf

layerrule = ignore_alpha 0.3, blur on, match:namespace bg_settings
layerrule = ignore_alpha 0, blur on, match:namespace side
layerrule = ignore_alpha 0, blur on, match:namespace bar
layerrule = ignore_alpha 0, match:namespace geom

windowrule=move (400) (510), match:title ^(fly_is_foot)$

decoration {
    rounding=0
    blur {
        enabled=1
        size=5
        passes=2
        noise=0.05
    }
    shadow {
        $OPACITY_HIGH = 55
        $OPACITY_LOW = 11
        color = rgba($BROWN$OPACITY_HIGH)
        color_inactive = rgba($BROWN$OPACITY_LOW)
        range = 1
        render_power = 1
        offset =5 5
    }
    screen_shader = $yorha/components/gridlines.frag
}

plugin {
    hyprbars {
        bar_height = 40
        bar_text_size = 17
        bar_text_font = FOT-Rodin Pro M
        bar_text_align = left
        bar_color = rgb($BROWN)
        col.text = rgb($TAN)
        hyprbars-button = rgb($BROWN), 30, ◬, hyprctl dispatch killactive
        hyprbars-button = rgb($BROWN), 30, ▽, hyprctl dispatch fullscreen 1
    }
    
    hyprtheme {
        theme = $yorha/components/hyprtheme/theme.toml
    }
}

general {
    col.active_border=0x00000000
    col.inactive_border=0x00000000
    border_size=0
    gaps_in = 20
    gaps_out = 20
}

animations {
    enabled=1
    bezier = in-out,0.65,-0.01,0,0.95
    bezier = woa,0,0,0,1
    animation=windows,1,2,woa,popin
    animation=border,1,10,default
    animation=fade,1,10,default
    animation=workspaces,1,5,in-out,slide
}

debug {
  disable_logs = false
}

misc {
    disable_hyprland_logo = true
    background_color = rgb($TAN_BG)
}