#!/usr/bin/bash

themedir=$1
grim -g "$(agsv1 -b geom -c $themedir/components/ags/windows/geom/geom.js)" /tmp/scrn.png && \
 wl-copy < /tmp/scrn.png && \
 notify-send "Screenshot copied to clipboard" -a "ss" -i /tmp/scrn.png